%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 07-Mar-2026 16:32:48
                     ConfigInfos.Version = '25.1.0.2943329 (R2025a)';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.LicStatus = [1,1,1,0,1,0,1,0,1];
                ConfigInfos.ProjPathText = '';
                    ConfigInfos.ProjPath = '/Users/miguelferreira/MATLAB/Projects/examples/VirtualVehicle2/VirtualVehicle';
                 ConfigInfos.SessionName = 'TeslaM3';
                 ConfigInfos.XmlPathText = '';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 1EM';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 3DOF Longitudinal';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 3DOF Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Front Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '1EM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 1EM)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'No Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'No Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'No Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'No IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'No Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Single-Speed Transmission 1EM';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 1EM with BMS';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '1851';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

           ConfigInfos.DataModified{2,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,2} = '1.495';
           ConfigInfos.DataModified{2,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{2,6} = 'Body and Frame';

           ConfigInfos.DataModified{3,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,2} = '1.380';
           ConfigInfos.DataModified{3,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{3,6} = 'Body and Frame';

           ConfigInfos.DataModified{4,1} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,2} = '0.13';
           ConfigInfos.DataModified{4,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{4,6} = 'Body and Frame';

           ConfigInfos.DataModified{5,1} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{5,2} = '2600';
           ConfigInfos.DataModified{5,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{5,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{5,6} = 'Body and Frame';

           ConfigInfos.DataModified{6,1} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{6,2} = '0.23';
           ConfigInfos.DataModified{6,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{6,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{6,6} = 'Body and Frame';

           ConfigInfos.DataModified{7,1} = 'PlntVehAeroLiftCff';
           ConfigInfos.DataModified{7,2} = '0';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehAeroLiftCff';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehAeroPitchCff';
           ConfigInfos.DataModified{8,2} = '0';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehAeroPitchCff';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

           ConfigInfos.DataModified{9,1} = 'PlntBattNumCellPar';
           ConfigInfos.DataModified{9,2} = '46';
           ConfigInfos.DataModified{9,3} = 'BatteryDCDC.sldd';
           ConfigInfos.DataModified{9,4} = 'PlntBattNumCellPar';
           ConfigInfos.DataModified{9,5} = 'Mapped Battery (Electric Vehicle 1EM)';
           ConfigInfos.DataModified{9,6} = 'Energy Storage';

          ConfigInfos.DataModified{10,1} = 'PlntBattChrgMax';
          ConfigInfos.DataModified{10,2} = '4.85';
          ConfigInfos.DataModified{10,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{10,4} = 'PlntBattChrgMax';
          ConfigInfos.DataModified{10,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{10,6} = 'Energy Storage';

          ConfigInfos.DataModified{11,1} = 'PlntCellMassEv';
          ConfigInfos.DataModified{11,2} = '0.069';
          ConfigInfos.DataModified{11,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{11,4} = 'PlntCellMassEv';
          ConfigInfos.DataModified{11,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{11,6} = 'Energy Storage';

%% Test Plan
                ConfigInfos.TestPlan=[];

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattCurr',...
};

%% Finish
